const PRESETS1 = [
  { name: 'Klein', hex: '#0033ff' },
  { name: 'Lemon', hex: '#fff44f' },
  { name: 'Plum', hex: '#5e2750' },
  { name: 'Mint', hex: '#98ff98' },
  { name: 'Tomato', hex: '#e54b2a' },
  { name: 'Petrol', hex: '#1f5f6b' },
  { name: 'Apricot', hex: '#ffb07c' },
  { name: 'Onyx', hex: '#0f0f0f' },
  { name: 'Hot Pink', hex: '#ff69b4' },
  { name: 'Sapphire', hex: '#0b3d91' },
  { name: 'Citron', hex: '#9fa91f' },
  { name: 'Lilac', hex: '#c8a2c8' },
  { name: 'Neon Grass', hex: '#39ff14' },
  { name: 'Rust', hex: '#8b3a1f' },
  { name: 'Aqua', hex: '#00ffd0' },
] as const

const PRESETS2 = [
  { name: 'Greige', hex: '#b8b0a1' },
  { name: 'Electric Purple', hex: '#bf00ff' },
  { name: 'Marigold', hex: '#ffa62b' },
  { name: 'Teal', hex: '#008f9b' },
  { name: 'Cherry', hex: '#d2042d' },
  { name: 'Periwinkle', hex: '#8da0ff' },
  { name: 'Pistachio', hex: '#b7d97a' },
  { name: 'Magenta', hex: '#ff00aa' },
  { name: 'Mustard', hex: '#c9a227' },
  { name: 'Pine', hex: '#2c4a3b' },
  { name: 'Sky', hex: '#5fa8ff' },
  { name: 'Cardinal', hex: '#9b1b30' },
  { name: 'Seafoam', hex: '#9fe2bf' },
  { name: 'Grape', hex: '#6f2da8' },
  { name: 'Pumpkin', hex: '#e8731f' },
] as const

const PRESETS3 = [
  { name: 'Salmon', hex: '#ff8c69' },
  { name: 'Azure', hex: '#1e7fff' },
  { name: 'Chartreuse', hex: '#dfff00' },
  { name: 'Byzantium', hex: '#702963' },
  { name: 'Jade', hex: '#00a86b' },
  { name: 'Flamingo', hex: '#fc8eac' },
  { name: 'Copper', hex: '#b66e41' },
  { name: 'Porcelain', hex: '#f4f1ec' },
  { name: 'Electric Cyan', hex: '#00f5ff' },
  { name: 'Rose', hex: '#e75480' },
  { name: 'Indigo', hex: '#2b1a8c' },
  { name: 'Moss', hex: '#5a6f3a' },
  { name: 'Caramel', hex: '#c68642' },
  { name: 'Slate', hex: '#4b5563' },
  { name: 'Lime', hex: '#7cff3f' },
] as const

const PRESETS4 = [
  { name: 'Ink', hex: '#0d1117' },
  { name: 'Scarlet', hex: '#ff2400' },
  { name: 'Pewter', hex: '#8a8d91' },
  { name: 'Amber', hex: '#ffbf00' },
  { name: 'Taupe', hex: '#8b7e74' },
  { name: 'Denim', hex: '#4a6fa5' },
  { name: 'Oat', hex: '#e3dcc8' },
  { name: 'Orchid', hex: '#c585d6' },
  { name: 'Mocha', hex: '#6f4e37' },
  { name: 'Turquoise', hex: '#1abc9c' },
  { name: 'Butter', hex: '#f3e5ab' },
  { name: 'Berry', hex: '#8e3a59' },
  { name: 'Powder', hex: '#b0c4de' },
  { name: 'Fern', hex: '#4f7942' },
  { name: 'Dusty Rose', hex: '#c08081' },
] as const

export { PRESETS1, PRESETS2, PRESETS3, PRESETS4 }
