const PRESETS1 = [
  { name: 'Cobalt', hex: '#2e5bff' },
  { name: 'Laser', hex: '#caff00' },
  { name: 'Wine', hex: '#722f37' },
  { name: 'Frost', hex: '#a9d6f5' },
  { name: 'Vermilion', hex: '#ff3b00' },
  { name: 'Mushroom', hex: '#a89a8c' },
  { name: 'Cyber', hex: '#9b5cff' },
  { name: 'Sunburst', hex: '#ffc400' },
  { name: 'Navy', hex: '#1b2a4a' },
  { name: 'Bubblegum', hex: '#ff5fa2' },
  { name: 'Olive', hex: '#6f7531' },
  { name: 'Voltage', hex: '#00e0ff' },
  { name: 'Brick', hex: '#9e3b2e' },
  { name: 'Lavender', hex: '#c4a7ff' },
  { name: 'Clover', hex: '#21c45d' },
  { name: 'Espresso', hex: '#2b2118' },
  { name: 'Tangerine', hex: '#ff6a1a' },
  { name: 'Sage', hex: '#478f5c' },
  { name: 'Iris', hex: '#7a2fff' },
  { name: 'Lagoon', hex: '#00c4c9' },
  { name: 'Ruby', hex: '#e54666' },
] as const

const PRESETS2 = [
  { name: 'Espresso', hex: '#2b2118' },
  { name: 'Coral', hex: '#ff6b6b' },
  { name: 'Ultramarine', hex: '#1e22ff' },
  { name: 'Sand', hex: '#d8c3a5' },
  { name: 'Fuchsia', hex: '#ff1f8f' },
  { name: 'Forest', hex: '#1f4d2e' },
  { name: 'Quartz', hex: '#e8b4bc' },
  { name: 'Tangelo', hex: '#ff7a00' },
  { name: 'Steel', hex: '#5a6b7d' },
  { name: 'Violet', hex: '#7b00ff' },
  { name: 'Terracotta', hex: '#c66a4f' },
  { name: 'Bone', hex: '#ece6da' },
  { name: 'Punch', hex: '#e91e63' },
  { name: 'Emerald', hex: '#0a7d54' },
  { name: 'Brat', hex: '#8ace00' },
  { name: 'Mauve', hex: '#a07d8f' },
] as const

const PRESETS3 = [
  { name: 'Gray', hex: '#161616' },
  { name: 'Coral', hex: '#abab9c' },
  { name: 'Ultramarine', hex: '#394447' },
  { name: 'Sand', hex: '#2a212c' },
  { name: 'Fuchsia', hex: '#3f3f46' },
  { name: 'Forest', hex: '#737373' },
  { name: 'Quartz', hex: '#1c1917' },
  { name: 'Tangelo', hex: '#2b2422' },
  { name: 'Steel', hex: '#aba09c' },
  { name: 'Violet', hex: '#45556c' },
  { name: 'Terracotta', hex: '#f1f5f9' },
  { name: 'Bone', hex: '#2b2b22' },
  { name: 'Punch', hex: '#090b0c' },
  { name: 'Emerald', hex: '#0c090c' },
  { name: 'Brat', hex: '#1d1816' },
  { name: 'Mauve', hex: '#101828' },
] as const

export { PRESETS1, PRESETS2, PRESETS3 }
