// Run with: pnpm bake (uses vite-node, bundled with vitest).
// why: globals.css is the first-paint default — read by Tailwind's PostCSS
// pipeline before React mounts. We bake it from deriveTheme(DEFAULT_INPUTS)
// so preview === export holds even before applyDom subscribes. ADR-0017.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DEFAULT_INPUTS, deriveTheme, formatCss } from '@tonex/core'

const here = dirname(fileURLToPath(import.meta.url))
const cssPath = join(here, '../src/app/globals.css')

const START_MARKER =
  '/* tonex:tokens:start — generated by scripts/bake-tokens.ts; do not hand-edit. */'
const END_MARKER = '/* tonex:tokens:end */'

const baked = formatCss(deriveTheme(DEFAULT_INPUTS))
const block = `${START_MARKER}\n${baked}\n${END_MARKER}`

const existing = readFileSync(cssPath, 'utf-8')
const blockRegex = /\/\* tonex:tokens:start[\s\S]*?\/\* tonex:tokens:end \*\//

const next = blockRegex.test(existing)
  ? existing.replace(blockRegex, block)
  : `${existing.trimEnd()}\n\n${block}\n`

writeFileSync(cssPath, next)
console.log(`baked ${baked.split('\n').length} lines into ${cssPath}`)
