import type { PresetFixture } from './bundle-snapshot'

// why: in-progress preset library — the durable artifact during the
// curation phase of issue #36. Edit by hand or paste-replace entries
// produced by the rail's Copy button. The engineering slice will promote
// the finalized bundles to `@tonex/core` as `SHADCN_PRESETS` (TDD); the
// fixture file gets deleted with the whole tuner folder when that ships.
//
// Add: paste a new fixture entry into the array.
// Delete: remove the entry.
// Adjust: open /theme/shadcn → Load preset → tune → Copy → paste-replace.
//
// Slugs are placeholders — rename freely. They show up in the Load picker
// so something memorable helps once there are 5+ entries.
export const PRESET_FIXTURES: PresetFixture[] = [
  // Preset: Default(Brand)
  {
    name: 'Default',
    bundle: {
      variant: 'cmf',
      surfaceAlgo: 'desaturate',
      surfacePaletteName: 'zinc',
      surfaceTintLevel: { light: 0, dark: 0 },
      surfaceDesaturateLevel: { light: 0, dark: 0 },
      shadcnRoleBindings: {
        light: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface-container',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface-container',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary-container',
          '--primary-foreground': '--color-on-primary-container',
          '--secondary': '--color-secondary-container',
          '--secondary-foreground': '--color-on-secondary-container',
          '--muted': '--color-surface-dim',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-surface-dim',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-outline',
          '--input': '--color-outline',
          '--ring': '--color-primary',
          '--sidebar': '--color-surface-container-low',
          '--sidebar-foreground': '--color-on-surface-variant',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-high',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-outline',
          '--sidebar-ring': '--color-outline',
        },
        dark: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface-container',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface-container',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary',
          '--primary-foreground': '--color-on-primary',
          '--secondary': '--color-secondary-container',
          '--secondary-foreground': '--color-on-secondary-container',
          '--muted': '--color-surface-bright',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-surface-bright',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-outline',
          '--input': '--color-outline',
          '--ring': '--color-primary',
          '--sidebar': '--color-surface-container-low',
          '--sidebar-foreground': '--color-on-surface-variant',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-highest',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-outline',
          '--sidebar-ring': '--color-outline',
        },
      },
    },
  },

  // Preset: Stark
  {
    name: 'Stark',
    bundle: {
      variant: 'cmf',
      surfaceAlgo: 'tint',
      surfacePaletteName: 'zinc',
      surfaceTintLevel: { light: 0, dark: 0 },
      surfaceDesaturateLevel: { light: 0, dark: 0 },
      shadcnRoleBindings: {
        light: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary-container',
          '--primary-foreground': '--color-on-primary-container',
          '--secondary': '--color-secondary-container',
          '--secondary-foreground': '--color-on-secondary-container',
          '--muted': '--color-surface-container-high',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-surface-container-high',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-outline-variant',
          '--input': '--color-outline-variant',
          '--ring': '--color-outline',
          '--sidebar': '--color-surface-container',
          '--sidebar-foreground': '--color-on-surface',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-high',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-outline-variant',
          '--sidebar-ring': '--color-outline',
        },
        dark: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary-container',
          '--primary-foreground': '--color-on-primary-container',
          '--secondary': '--color-secondary-container',
          '--secondary-foreground': '--color-on-secondary-container',
          '--muted': '--color-surface-container',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-surface-container-high',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-outline-variant',
          '--input': '--color-outline-variant',
          '--ring': '--color-outline',
          '--sidebar': '--color-surface-container',
          '--sidebar-foreground': '--color-on-surface',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-high',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-outline-variant',
          '--sidebar-ring': '--color-outline',
        },
      },
    },
  },
  // Preset: Soft
  {
    name: 'Soft',
    bundle: {
      variant: 'tonalSpot',
      surfaceAlgo: 'desaturate',
      surfacePaletteName: 'stone',
      surfaceTintLevel: { light: 0.1, dark: 0.3 },
      surfaceDesaturateLevel: { light: 0.2, dark: 1 },
      shadcnRoleBindings: {
        light: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface-container',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface-container',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary',
          '--primary-foreground': '--color-on-primary',
          '--secondary': '--color-secondary-container',
          '--secondary-foreground': '--color-on-secondary-container',
          '--muted': '--color-surface-container-high',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-surface-container-highest',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-outline-variant',
          '--input': '--color-outline-variant',
          '--ring': '--color-outline',
          '--sidebar': '--color-surface-container-low',
          '--sidebar-foreground': '--color-on-surface',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-high',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-outline-variant',
          '--sidebar-ring': '--color-outline',
        },
        dark: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface-container',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface-container',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary',
          '--primary-foreground': '--color-on-primary',
          '--secondary': '--color-secondary-container',
          '--secondary-foreground': '--color-on-secondary-container',
          '--muted': '--color-surface-container-high',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-surface-container-highest',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-outline-variant',
          '--input': '--color-outline-variant',
          '--ring': '--color-outline',
          '--sidebar': '--color-surface-container-low',
          '--sidebar-foreground': '--color-on-surface-variant',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-highest',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-outline-variant',
          '--sidebar-ring': '--color-outline',
        },
      },
    },
  },
  // Preset: Warm
  {
    name: 'Warm',
    bundle: {
      variant: 'cmf',
      surfaceAlgo: 'tint',
      surfacePaletteName: 'taupe',
      surfaceTintLevel: { light: 0.1, dark: 0.1 },
      surfaceDesaturateLevel: { light: 0, dark: 1 },
      shadcnRoleBindings: {
        light: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface-container',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface-container',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary-container',
          '--primary-foreground': '--color-on-primary-container',
          '--secondary': '--color-secondary',
          '--secondary-foreground': '--color-on-secondary',
          '--muted': '--color-surface-container-high',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-surface-container-high',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-outline-variant',
          '--input': '--color-outline-variant',
          '--ring': '--color-outline-variant',
          '--sidebar': '--color-surface-container',
          '--sidebar-foreground': '--color-on-surface-variant',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-high',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-outline-variant',
          '--sidebar-ring': '--color-outline-variant',
        },
        dark: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface-container',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface-container',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary-container',
          '--primary-foreground': '--color-on-primary-container',
          '--secondary': '--color-secondary-container',
          '--secondary-foreground': '--color-on-secondary-container',
          '--muted': '--color-surface-container-high',
          '--muted-foreground': '--color-on-surface',
          '--accent': '--color-surface-container-high',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-outline-variant',
          '--input': '--color-outline-variant',
          '--ring': '--color-outline',
          '--sidebar': '--color-surface-container',
          '--sidebar-foreground': '--color-on-surface-variant',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-high',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-outline-variant',
          '--sidebar-ring': '--color-outline-variant',
        },
      },
    },
  },
  // Preset: Playful
  {
    name: 'Playful',
    bundle: {
      variant: 'expressive',
      surfaceAlgo: 'desaturate',
      surfacePaletteName: 'mauve',
      surfaceTintLevel: { light: 1, dark: 0 },
      surfaceDesaturateLevel: { light: 0, dark: 0 },
      shadcnRoleBindings: {
        light: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary',
          '--primary-foreground': '--color-on-primary',
          '--secondary': '--color-tertiary-container',
          '--secondary-foreground': '--color-on-tertiary-container',
          '--muted': '--color-surface-container',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-tertiary-container',
          '--accent-foreground': '--color-on-tertiary-container',
          '--destructive': '--color-error',
          '--border': '--color-tertiary-fixed-dim',
          '--input': '--color-tertiary-fixed-dim',
          '--ring': '--color-tertiary-fixed-dim',
          '--sidebar': '--color-surface-container-low',
          '--sidebar-foreground': '--color-on-surface',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-tertiary-container',
          '--sidebar-accent-foreground': '--color-on-tertiary-container',
          '--sidebar-border': '--color-outline',
          '--sidebar-ring': '--color-outline',
        },
        dark: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary',
          '--primary-foreground': '--color-on-primary',
          '--secondary': '--color-tertiary-container',
          '--secondary-foreground': '--color-on-tertiary-container',
          '--muted': '--color-surface-container',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-tertiary-container',
          '--accent-foreground': '--color-on-tertiary-container',
          '--destructive': '--color-error',
          '--border': '--color-tertiary-container',
          '--input': '--color-tertiary-container',
          '--ring': '--color-tertiary',
          '--sidebar': '--color-surface-container-low',
          '--sidebar-foreground': '--color-on-surface',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-tertiary-container',
          '--sidebar-accent-foreground': '--color-on-tertiary-container',
          '--sidebar-border': '--color-tertiary-container',
          '--sidebar-ring': '--color-tertiary',
        },
      },
    },
  },
  // Preset: Monotone
  {
    name: 'Monotone',
    bundle: {
      variant: 'monochrome',
      surfaceAlgo: 'tint',
      surfacePaletteName: 'zinc',
      surfaceTintLevel: { light: 0, dark: 0 },
      surfaceDesaturateLevel: { light: 0, dark: 0 },
      shadcnRoleBindings: {
        light: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary',
          '--primary-foreground': '--color-on-primary',
          '--secondary': '--color-secondary-container',
          '--secondary-foreground': '--color-on-secondary-container',
          '--muted': '--color-surface-container-high',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-surface-container-high',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-outline-variant',
          '--input': '--color-outline-variant',
          '--ring': '--color-outline',
          '--sidebar': '--color-surface-container-low',
          '--sidebar-foreground': '--color-on-surface',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-highest',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-outline',
          '--sidebar-ring': '--color-outline',
        },
        dark: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface-container',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary',
          '--primary-foreground': '--color-on-primary',
          '--secondary': '--color-secondary-container',
          '--secondary-foreground': '--color-on-secondary-container',
          '--muted': '--color-surface-container-highest',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-surface-container-highest',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-outline-variant',
          '--input': '--color-outline-variant',
          '--ring': '--color-outline',
          '--sidebar': '--color-surface-container',
          '--sidebar-foreground': '--color-on-surface',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-highest',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-outline',
          '--sidebar-ring': '--color-outline',
        },
      },
    },
  },
  // Preset: Tech
  {
    name: 'Tech',
    bundle: {
      variant: 'rainbow',
      surfaceAlgo: 'tint',
      surfacePaletteName: 'mist',
      surfaceTintLevel: { light: 0.5, dark: 0.5 },
      surfaceDesaturateLevel: { light: 0, dark: 0 },
      shadcnRoleBindings: {
        light: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary-container',
          '--primary-foreground': '--color-on-primary-container',
          '--secondary': '--color-secondary-container',
          '--secondary-foreground': '--color-on-secondary-container',
          '--muted': '--color-surface-container',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-surface-container-high',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-primary-container',
          '--input': '--color-primary-container',
          '--ring': '--color-primary-container',
          '--sidebar': '--color-surface-container-low',
          '--sidebar-foreground': '--color-on-surface-variant',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-high',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-outline',
          '--sidebar-ring': '--color-outline',
        },
        dark: {
          '--background': '--color-surface',
          '--foreground': '--color-on-surface',
          '--card': '--color-surface',
          '--card-foreground': '--color-on-surface',
          '--popover': '--color-surface',
          '--popover-foreground': '--color-on-surface',
          '--primary': '--color-primary',
          '--primary-foreground': '--color-on-primary',
          '--secondary': '--color-secondary',
          '--secondary-foreground': '--color-on-secondary',
          '--muted': '--color-surface-dim',
          '--muted-foreground': '--color-on-surface-variant',
          '--accent': '--color-surface-container-high',
          '--accent-foreground': '--color-on-surface',
          '--destructive': '--color-error',
          '--border': '--color-primary-container',
          '--input': '--color-primary-container',
          '--ring': '--color-surface-tint',
          '--sidebar': '--color-surface-dim',
          '--sidebar-foreground': '--color-on-surface-variant',
          '--sidebar-primary': '--color-primary',
          '--sidebar-primary-foreground': '--color-on-primary',
          '--sidebar-accent': '--color-surface-container-high',
          '--sidebar-accent-foreground': '--color-on-surface',
          '--sidebar-border': '--color-primary',
          '--sidebar-ring': '--color-surface-tint',
        },
      },
    },
  },
]
