'use client'

import { exportCss, useResolvedTokens, useSource } from '@tonex/core'
import { useMemo } from 'react'

export type ExportTab = 'Tailwind' | 'shadcn' | 'TS' | 'JSON' | 'Dart'

// why: Tailwind tab emits the md layer (full globals.css with @theme inline);
// shadcn tab emits :root + .dark only since the user already owns the @import
// and @theme inline in their shadcn project. Both go through core's exportCss
// so the drift-guard (ADR-0017) covers what users actually paste. TS / JSON /
// Dart are placeholders — we ship the tabs visible so users see the roadmap,
// but render a TODO body until the formatters land in core.
const STUB_TS = `// TS export — coming soon.
// Will produce a typed const map of all md tokens (light + dark), suitable
// for design-token consumption from JS/TS code (Storybook, RN, etc).
`

const STUB_JSON = `{
  "_comment": "JSON export — coming soon. Will follow the design-token-community-group spec, mode-keyed (light/dark) with the full md token surface."
}
`

const STUB_DART = `// Dart export — coming soon.
// Will produce ColorScheme + per-mode ThemeData for a Flutter app consuming
// the same source-of-truth tokens.
`

function formatHeader(seed: string, variant: string, contrast: number, spec: string): string {
  return [
    '/*',
    ' * Generated by tonex',
    ` * source: ${seed} · variant: ${variant} · contrast: ${contrast} · spec: ${spec}`,
    ' */',
    '',
    '',
  ].join('\n')
}

export interface ExportContent {
  exportContent: string
  ext: string
}

export function useExportContent({ exportTab }: { exportTab: ExportTab }): ExportContent {
  const theme = useResolvedTokens()
  const seedHex = useSource((s) => s.seedHex)
  const variant = useSource((s) => s.variant)
  const contrastLevel = useSource((s) => s.contrastLevel)

  return useMemo(() => {
    if (exportTab === 'TS') return { exportContent: STUB_TS, ext: 'ts' }
    if (exportTab === 'JSON') return { exportContent: STUB_JSON, ext: 'json' }
    if (exportTab === 'Dart') return { exportContent: STUB_DART, ext: 'dart' }

    if (!theme) return { exportContent: '/* Loading… */', ext: 'css' }

    // why: SchemeCmf hardcodes specVersion '2026'; everything else inherits
    // DynamicScheme.DEFAULT_SPEC_VERSION ('2021'). Surface this in the header
    // so users re-importing know which spec the values were derived under.
    const spec = variant === 'cmf' ? '2026' : '2021'
    const header = formatHeader(seedHex, variant, contrastLevel, spec)
    const layer = exportTab === 'Tailwind' ? 'md' : 'shadcn'
    return { exportContent: header + exportCss(theme, layer), ext: 'css' }
  }, [exportTab, theme, seedHex, variant, contrastLevel])
}
