import { describe, expect, it } from 'vitest'
import { formatHeader } from './use-export-content'

// why: the export header is the provenance trail a user reads to recover the
// source state. contrast is the only field with a baseline value (0 = MCU
// default, no adjustment) — emitting `contrast: 0` reads as an applied
// setting and is noise. Omit at baseline; emit verbatim for any non-zero
// level so re-importers can recover the value unchanged. Source state
// clamps to [0, 1] (issue #33) so the equality check is exact.
describe('formatHeader', () => {
  it('omits `contrast` when level is 0 (baseline)', () => {
    const out = formatHeader('#6750a4', 'cmf', 0, '2026')
    expect(out).toContain('source: #6750a4 · variant: cmf · spec: 2026')
    expect(out).not.toContain('contrast:')
  })

  it('emits `contrast` verbatim when level is non-zero', () => {
    const out = formatHeader('#6750a4', 'tonalSpot', 0.5, '2021')
    expect(out).toContain('source: #6750a4 · variant: tonalSpot · contrast: 0.5 · spec: 2021')
  })

  it('emits `contrast: 1` at the upper bound', () => {
    const out = formatHeader('#6750a4', 'tonalSpot', 1, '2021')
    expect(out).toContain('contrast: 1')
  })

  it('wraps the line in a /* */ comment block', () => {
    const out = formatHeader('#6750a4', 'cmf', 0, '2026')
    expect(out.startsWith('/*\n * Generated by tonex')).toBe(true)
    expect(out).toContain(' */')
  })
})
