import { describe, expect, it } from 'vitest'
import { formatHeader } from './use-export-content'

// why: the export header is the provenance trail a user reads to recover the
// source state. contrast is per-mode (#123) and the only field with a baseline
// value (0 = MCU default, no adjustment) — emitting `contrast: 0` reads as an
// applied setting and is noise. Omit when both modes are baseline; emit a
// single value when light === dark and `light/dark` when they diverge, so
// re-importers can recover the value unchanged. Source state clamps each mode
// to [0, 1] (issue #33) so the equality check is exact.
describe('formatHeader', () => {
  it('omits `contrast` when both modes are 0 (baseline)', () => {
    const out = formatHeader('#6750a4', 'cmf', { light: 0, dark: 0 }, '2026-05-13')
    expect(out).toContain('source: #6750a4 · variant: cmf · date: 2026-05-13')
    expect(out).not.toContain('contrast:')
  })

  it('emits a single `contrast` value when both modes match', () => {
    const out = formatHeader('#6750a4', 'tonalSpot', { light: 0.5, dark: 0.5 }, '2026-05-13')
    expect(out).toContain('source: #6750a4 · variant: tonalSpot · contrast: 0.5 · date: 2026-05-13')
  })

  it('emits `light/dark` when the modes diverge', () => {
    const out = formatHeader('#6750a4', 'tonalSpot', { light: 0, dark: 0.8 }, '2026-05-13')
    expect(out).toContain('contrast: 0/0.8')
  })

  it('emits the pair even when only one mode is non-zero', () => {
    const out = formatHeader('#6750a4', 'tonalSpot', { light: 1, dark: 1 }, '2026-05-13')
    expect(out).toContain('contrast: 1')
  })

  it('wraps the line in a /* */ comment block', () => {
    const out = formatHeader('#6750a4', 'cmf', { light: 0, dark: 0 }, '2026-05-13')
    expect(out.startsWith('/*\n * Generated by tonex')).toBe(true)
    expect(out).toContain(' */')
  })
})
