'use client'

import {
  buildContrastBundle,
  type ExportOptions,
  exportCss,
  exportDart,
  exportJson,
  exportNativeCss,
  selectPortable,
  selectSeedHex,
  useSource,
} from '@tonex/core'
import { useMemo } from 'react'
import { useShallow } from 'zustand/react/shallow'

export type ExportTab = 'Tailwind' | 'CSS' | 'shadcn' | 'JSON' | 'Dart'

// why: Tailwind tab emits the md layer (full globals.css with @theme inline);
// shadcn tab emits :root + .dark only since the user already owns the @import
// and @theme inline in their shadcn project. CSS tab emits framework-agnostic
// Material Design custom properties (`--md-sys-color-*`, one light-dark() pair
// per token) for non-Tailwind / Material Web consumers. All three go through
// core's exporters so the drift-guard (ADR-0017) covers what users actually
// paste. JSON and Dart have real formatters in
// `@tonex/core/exporters/{json,dart}.ts`.

// why: header is the export's provenance trail. seed + variant always carry
// signal; date is what users actually find useful when comparing two pasted
// exports in a project. contrast is the only field with a baseline value
// (0 = no adjustment, MCU default); emitting `contrast: 0` reads as applied
// where none is. Omit at baseline; emit verbatim otherwise so re-importers
// can recover non-default contrast unchanged. Source state clamps contrast
// to [0, 1] (issue #33) so the equality check is exact.
export function formatHeader(
  seed: string,
  variant: string,
  contrast: number,
  date: string,
): string {
  const parts = [`source: ${seed}`, `variant: ${variant}`]
  if (contrast !== 0) parts.push(`contrast: ${contrast}`)
  parts.push(`date: ${date}`)
  return ['/*', ' * Generated by Tonex', ` * ${parts.join(' · ')}`, ' */', '', ''].join('\n')
}

export interface ExportContent {
  exportContent: string
  ext: string
}

export function useExportContent({
  exportTab,
  options,
}: {
  exportTab: ExportTab
  options: ExportOptions
}): ExportContent {
  const hydrated = useSource((s) => s._hydrated)
  // why: useShallow + selectPortable mirrors useResolvedTokens — one stable
  // PortableTheme reference per source change. buildContrastBundle routes
  // through the unified derive cache (issue #20), keyed on (source,
  // contrastLevel), so toggling format-only flags doesn't re-derive the
  // (potentially 3×) tier set and the default tier shares its slot with
  // useResolvedTokens / applyDom.
  const portable = useSource(useShallow(selectPortable))
  const seedHex = useSource(selectSeedHex)
  const variant = useSource((s) => s.variant)
  const contrastLevel = useSource((s) => s.contrastLevel)

  return useMemo(() => {
    if (!hydrated) return { exportContent: '/* Loading… */', ext: 'css' }

    // why: ADR-0021 commitment 5 — buildContrastBundle is lazy and shared by the
    // JSON and CSS paths, so it's built once below the hydration guard. Toggling
    // includeContrastVariants triggers the 3× derive only on dialog mount /
    // option change, not on every source render. WYSIWYG-visibility per
    // commitment 7 — the string we hand to the dialog pane equals what the user
    // pastes byte-for-byte.
    const bundle = buildContrastBundle(portable, options)

    // why: the JSON branch lives below the hydration guard (#84) — it needs the
    // derived bundle + source. exportJson reshapes the same DerivedTheme the CSS
    // path uses into MTB-shaped JSON (ADR-0029).
    if (exportTab === 'JSON') {
      return { exportContent: exportJson(portable, bundle, options), ext: 'json' }
    }

    // why: Dart joined the bundle-consuming branches in slice dart-1 — it
    // reshapes the same DerivedTheme into a Flutter MaterialTheme (ADR-0021
    // c.9). options gate the tiers (dart-2 contrast) and the standalone
    // ChartColors class (dart-3 includeChart).
    if (exportTab === 'Dart') return { exportContent: exportDart(bundle, options), ext: 'dart' }

    // why: ISO yyyy-mm-dd — sortable, locale-free, and the form users expect
    // to see in a generated-file banner. Captured at memo recompute time so
    // the header reflects when the user actually generated this export.
    const date = new Date().toISOString().slice(0, 10)
    const header = formatHeader(seedHex, variant, contrastLevel, date)

    // why: the CSS tab is framework-agnostic native CSS (light-dark() pairs,
    // optional --md-sys-color-* namespace), a separate exporter from the
    // Tailwind/shadcn `md`/`shadcn` layers. Same provenance header.
    if (exportTab === 'CSS') {
      return { exportContent: header + exportNativeCss(bundle, options), ext: 'css' }
    }

    const layer = exportTab === 'Tailwind' ? 'md' : 'shadcn'
    return { exportContent: header + exportCss(bundle, layer, options), ext: 'css' }
  }, [exportTab, hydrated, portable, options, seedHex, variant, contrastLevel])
}
